name: chatgpt
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  http: ^1.2.2
  fpdart: ^1.1.0
  flutter_bloc: ^8.1.6
  get_it: ^8.0.0
  flutter_dotenv: ^5.2.1
  typewritertext: ^3.0.9
  shared_preferences: ^2.3.3
  uuid: ^4.5.1
dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^4.0.0


flutter:

 
  uses-material-design: true
assets:
 - assets/chatgpt.jpg
 - .env
 
